=== nicktodd/mapforce-labs/schemas/music.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by Nick Todd (Conygre Consultants) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="albums">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="album" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:positiveInteger" minOccurs="0"/>
							<xs:element name="title" type="xs:string"/>
							<xs:element name="artist" type="xs:string"/>
							<xs:element name="price" type="xs:double"/>
							<xs:element name="tracks" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="track" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicktodd/mapforce-labs/data/music.xml
<?xml version="1.1" encoding="UTF-8"?>
<albums xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/GitRepos/mapforce-labs/schemas/music.xsd">
	<album>
		<title>Pressure Machine</title>
		<artist>Killers</artist>
		<price>13.99</price>
	</album>
	<album>
		<title>Sour</title>
		<artist>Olivia Rodrigo</artist>
		<price>10.99</price>
	</album>
	<album>
		<title>Happier than Ever</title>
		<artist>Billy Eilish</artist>
		<price>11.99</price>
	</album>
	<album>
		<title>Therapy</title>
		<artist>Anne-Marie</artist>
		<price>9.99</price>
	</album>
	<album>
		<title>Divide</title>
		<artist>ed Sheeran</artist>
		<price>14.99</price>
	</album>
	<album>
		<title>All Over the Place</title>
		<artist>KSI</artist>
		<price>13.99</price>
	</album>
	<album>
		<title>Divinely Uninspired to the Hellish Extent</title>
		<artist>Lewis Capaldi</artist>
		<price>12.99</price>
	</album>
	<album>
		<title>Number Ones</title>
		<artist>Michael Jackson</artist>
		<price>4.99</price>
		<tracks>
			<track>Thriller</track>
			<track>Billy Jean</track>
			<track>Beat It</track>
		</tracks>
	</album>
	<album>
		<title>Justice</title>
		<artist>Justin Bieber</artist>
		<price>10</price>
	</album>
</albums>
