=== nicktodd/mapforce-labs/schemas/scores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by Nick Todd (Conygre Consultants) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="scores">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="score" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="studentCode" type="xs:string"/>
							<xs:element name="percentage" type="xs:int"/>
							<xs:element name="dateCompleted" type="xs:date"/>
							<xs:element name="timeSubmitted" type="xs:time"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nicktodd/mapforce-labs/schemas/scores.xml
<?xml version="1.0" encoding="utf-8"?>
<scores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/GitRepos/mapforce-labs/schemas/scores.xsd">
	<score>
		<studentCode>NYAD25</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:34:54.49</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD27</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:35:53.036</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD26</studentCode>
		<percentage>76</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:36:02.237</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD35</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:36:20.874</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD45</studentCode>
		<percentage>76</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:36:37.378</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD23</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:36:52.685</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD8</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:36:58.495</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD16</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:01.261</timeSubmitted>
	</score>
	<score>
		<studentCode>TAMPAAD13</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:03.092</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD42</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:03.351</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD17</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:12.015</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD14</studentCode>
		<percentage>76</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:18.615</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD9</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:21.429</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD27</studentCode>
		<percentage>76</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:28.699</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD38</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:45.796</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD6</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:47.704</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD14</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:54.12</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD12</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:56.209</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD15</studentCode>
		<percentage>71</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:56.809</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD34</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:58.882</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD14</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:07.635</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD24</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:10.2849999</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD4</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:16.454</timeSubmitted>
	</score>
	<score>
		<studentCode>TAMPAAD2</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:24.577</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD40</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:25.959</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD3</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:48.488</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD21</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:53.002</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD11</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:38:55.457</timeSubmitted>
	</score>
	<score>
		<studentCode>TAMPAAD19</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:04.784</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD20</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:05.677</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD36</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:10.252</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD1</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:12.732</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD14</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:14.079</timeSubmitted>
	</score>
	<score>
		<studentCode>TAMPAAD21</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:17.826</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD14</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:37:33.2829999</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD28</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:22.155</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD19</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:32.601</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD11</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:49.477</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD7</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:39:55.342</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD10</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:40:00.514</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD24</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:40:12.271</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD5</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:40:15.906</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD2</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:40:19.117</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD30</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:40:25.403</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD31</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:40:29.725</timeSubmitted>
	</score>
	<score>
		<studentCode>TAMPAAD5</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:41:03.87</timeSubmitted>
	</score>
	<score>
		<studentCode>TAMPAAD7</studentCode>
		<percentage>76</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:41:06.07</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD15</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:41:28.706</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD37</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:41:50.65</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD7</studentCode>
		<percentage>100</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:41:51.343</timeSubmitted>
	</score>
	<score>
		<studentCode>NYAD8</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:41:52.428</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD43</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:41:56.371</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD23</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:42:13.103</timeSubmitted>
	</score>
	<score>
		<studentCode>TAMPAAD6</studentCode>
		<percentage>94</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:42:48.385</timeSubmitted>
	</score>
	<score>
		<studentCode>TampaAD17</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
		<timeSubmitted>20:42:53.864</timeSubmitted>
	</score>
	<score>
		<studentCode>MISAD47</studentCode>
		<percentage>88</percentage>
		<dateCompleted>2021-08-24</dateCompleted>
